/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Helper.DBConnection;
import Model.Bashekim;
import Model.Doctor;
import Model.Hasta;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class LogınGUI extends javax.swing.JFrame {

    private DBConnection conn = new DBConnection();

    public LogınGUI() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/icons/Hospital32.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        w_pane = new javax.swing.JPanel();
        logınLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        hastaLogın = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fld_hastaTC = new javax.swing.JTextField();
        fld_hastaPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        doctorLogın = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fld_doctorTC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fld_doctorPass = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hastane Otomasyonu");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        w_pane.setBackground(new java.awt.Color(255, 255, 255));
        w_pane.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        w_pane.setInheritsPopupMenu(true);
        w_pane.setMinimumSize(new java.awt.Dimension(500, 400));
        w_pane.setName(""); // NOI18N
        w_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logınLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Caduceus50.png"))); // NOI18N
        w_pane.add(logınLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 169, 68));
        jLabel1.setText("Hastane Yönetim Sistemine Hoşgeldiniz");
        w_pane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(100, 169, 68));

        hastaLogın.setBackground(new java.awt.Color(255, 255, 255));
        hastaLogın.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 169, 68)));
        hastaLogın.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 169, 68));
        jLabel2.setText("T.C. Numaranız:");
        hastaLogın.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 169, 68));
        jLabel3.setText("Şifre:");
        hastaLogın.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        fld_hastaTC.setBackground(new java.awt.Color(255, 255, 255));
        fld_hastaTC.setForeground(new java.awt.Color(0, 0, 0));
        hastaLogın.add(fld_hastaTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, 30));

        fld_hastaPass.setBackground(new java.awt.Color(255, 255, 255));
        fld_hastaPass.setForeground(new java.awt.Color(0, 0, 0));
        hastaLogın.add(fld_hastaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 280, 30));

        jButton1.setBackground(new java.awt.Color(100, 169, 68));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kayıt ol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        hastaLogın.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 40));

        jButton2.setBackground(new java.awt.Color(100, 169, 68));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Giriş Yap");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        hastaLogın.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 230, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bu alan boş bırakılamaz");
        hastaLogın.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bu alan boş bırakılamaz");
        hastaLogın.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, -1));

        jTabbedPane1.addTab("Hasta Girişi", hastaLogın);

        doctorLogın.setBackground(new java.awt.Color(255, 255, 255));
        doctorLogın.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 169, 68)));
        doctorLogın.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 169, 68));
        jLabel4.setText("T.C. Numaranız:");
        doctorLogın.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        fld_doctorTC.setBackground(new java.awt.Color(255, 255, 255));
        fld_doctorTC.setForeground(new java.awt.Color(0, 0, 0));
        doctorLogın.add(fld_doctorTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 169, 68));
        jLabel5.setText("Şifre:");
        doctorLogın.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        fld_doctorPass.setBackground(new java.awt.Color(255, 255, 255));
        fld_doctorPass.setForeground(new java.awt.Color(0, 0, 0));
        doctorLogın.add(fld_doctorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 280, 30));

        jButton3.setBackground(new java.awt.Color(100, 169, 68));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Giriş Yap");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        doctorLogın.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 460, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bu alan boş bırakılamaz");
        doctorLogın.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bu alan boş bırakılamaz");
        doctorLogın.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        jTabbedPane1.addTab("Doktor Girişi", doctorLogın);

        w_pane.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 480, 200));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Hasta");

        getContentPane().add(w_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegisterGUI rGUI = new RegisterGUI();
        rGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (fld_hastaTC.getText().length() == 0 && fld_hastaPass.getText().length() == 0) {
            jLabel6.setForeground(Color.red);
            jLabel7.setForeground(Color.red);
        } else {
            try {
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM user");

                while (rs.next()) {
                    if (fld_hastaTC.getText().equals(rs.getString("tcno")) && fld_hastaPass.getText().equals(rs.getString("password"))) {
                        if (rs.getString("type").equals("Hasta")) {
                            Hasta hasta = new Hasta();
                            hasta.setId(rs.getInt("id"));
                            hasta.setTcno(rs.getString("tcno"));
                            hasta.setName(rs.getString("name"));
                            hasta.setPassword(rs.getString("password"));
                            hasta.setType(rs.getString("type"));
                            HastaGUI hGUI = new HastaGUI(hasta);
                            hGUI.setVisible(true);
                            dispose();
                        }

                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (fld_doctorTC.getText().length() == 0 && fld_doctorPass.getText().length() == 0) {
            jLabel9.setForeground(Color.red);
            jLabel8.setForeground(Color.red);
        } else {
            try {
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM user");
                while (rs.next()) {
                    if (fld_doctorTC.getText().equals(rs.getString("tcno")) && fld_doctorPass.getText().equals(rs.getString("password"))) {
                        if (rs.getString("type").equals("Bashekim")) {
                            Bashekim bhekim = new Bashekim();
                            bhekim.setId(rs.getInt("id"));
                            bhekim.setTcno(rs.getString("tcno"));
                            bhekim.setName(rs.getString("name"));
                            bhekim.setPassword(rs.getString("password"));
                            bhekim.setType(rs.getString("type"));
                            BashekimGUI bGUI = new BashekimGUI(bhekim);
                            bGUI.setVisible(true);
                            dispose();
                        }
                        if (rs.getString("type").equals("Doktor")) {
                            Doctor dr = new Doctor();
                            dr.setId(rs.getInt("id"));
                            dr.setTcno(rs.getString("tcno"));
                            dr.setName(rs.getString("name"));
                            dr.setPassword(rs.getString("password"));
                            dr.setType(rs.getString("type"));
                            DoctorGUI dGUI = new DoctorGUI(dr);
                            dGUI.setVisible(true);
                            dispose();

                        }
                    }

                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogınGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel doctorLogın;
    private javax.swing.JPasswordField fld_doctorPass;
    private javax.swing.JTextField fld_doctorTC;
    private javax.swing.JPasswordField fld_hastaPass;
    private javax.swing.JTextField fld_hastaTC;
    private javax.swing.JPanel hastaLogın;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logınLogo;
    private javax.swing.JPanel w_pane;
    // End of variables declaration//GEN-END:variables
}
