/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Hasta;
import static View.BashekimGUI.bashekim;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import jdk.nashorn.api.tree.BreakTree;

/**
 *
 * @author user
 */
public class RegisterGUI extends javax.swing.JFrame {

    private static Hasta hasta = new Hasta();

    public RegisterGUI() {
        initComponents();

        Image icon = new ImageIcon(this.getClass().getResource("/icons/Hospital32.png")).getImage();
        this.setIconImage(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        w_panel = new javax.swing.JPanel();
        logınLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userName_field = new javax.swing.JTextField();
        tckn_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        confirm_field = new javax.swing.JPasswordField();
        btn_create = new javax.swing.JButton();
        label_geridön = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        error4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        w_panel.setBackground(new java.awt.Color(255, 255, 255));
        w_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logınLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Caduceus50.png"))); // NOI18N
        w_panel.add(logınLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel1.setBackground(new java.awt.Color(100, 169, 68));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 169, 68));
        jLabel1.setText("Hasta Kayıt Ekranı");
        w_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 320, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 169, 68));
        jLabel2.setText("Ad Soyad");
        w_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 25));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 169, 68));
        jLabel3.setText("TCNO");
        w_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 25));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 169, 68));
        jLabel4.setText("Şifreyi Doğrulayın");
        w_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 169, 68));
        jLabel5.setText("Şifre");
        w_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 25));

        userName_field.setBackground(new java.awt.Color(255, 255, 255));
        userName_field.setForeground(new java.awt.Color(0, 0, 0));
        userName_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 169, 68)));
        userName_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userName_fieldMouseClicked(evt);
            }
        });
        userName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_fieldActionPerformed(evt);
            }
        });
        userName_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userName_fieldKeyPressed(evt);
            }
        });
        w_panel.add(userName_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 25));

        tckn_field.setBackground(new java.awt.Color(255, 255, 255));
        tckn_field.setForeground(new java.awt.Color(0, 0, 0));
        tckn_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 169, 68)));
        tckn_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tckn_fieldMouseClicked(evt);
            }
        });
        tckn_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tckn_fieldActionPerformed(evt);
            }
        });
        tckn_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tckn_fieldKeyPressed(evt);
            }
        });
        w_panel.add(tckn_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 170, 25));

        password_field.setBackground(new java.awt.Color(255, 255, 255));
        password_field.setForeground(new java.awt.Color(0, 0, 0));
        password_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 169, 68)));
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_fieldKeyPressed(evt);
            }
        });
        w_panel.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 170, 25));

        confirm_field.setBackground(new java.awt.Color(255, 255, 255));
        confirm_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 169, 68)));
        confirm_field.setCaretColor(new java.awt.Color(0, 0, 0));
        confirm_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_fieldActionPerformed(evt);
            }
        });
        confirm_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirm_fieldKeyPressed(evt);
            }
        });
        w_panel.add(confirm_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 170, 25));

        btn_create.setBackground(new java.awt.Color(100, 169, 68));
        btn_create.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_create.setForeground(new java.awt.Color(255, 255, 255));
        btn_create.setText("Kayıt ol");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        w_panel.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 300, 40));

        label_geridön.setBackground(new java.awt.Color(255, 255, 255));
        label_geridön.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        label_geridön.setForeground(new java.awt.Color(100, 169, 68));
        label_geridön.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_geridön.setText("Geri dön");
        label_geridön.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_geridönMouseClicked(evt);
            }
        });
        w_panel.add(label_geridön, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 240, 20));

        error1.setForeground(new java.awt.Color(255, 255, 255));
        error1.setText("Bu kısım boş bırakılamaz");
        w_panel.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 170, -1));

        error2.setForeground(new java.awt.Color(255, 255, 255));
        error2.setText("Bu kısım boş bırakılamaz");
        w_panel.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 170, -1));

        error3.setForeground(new java.awt.Color(255, 255, 255));
        error3.setText("Bu kısım boş bırakılamaz");
        w_panel.add(error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 170, -1));

        error4.setForeground(new java.awt.Color(255, 255, 255));
        error4.setText("Bu kısım boş bırakılamaz");
        w_panel.add(error4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 170, -1));

        getContentPane().add(w_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed

    }//GEN-LAST:event_password_fieldActionPerformed

    private void userName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_fieldActionPerformed

    }//GEN-LAST:event_userName_fieldActionPerformed

    private void confirm_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_fieldActionPerformed

    }//GEN-LAST:event_confirm_fieldActionPerformed

    private void label_geridönMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_geridönMouseClicked
        LogınGUI lGUI = new LogınGUI();
        lGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_label_geridönMouseClicked

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        if (!password_field.getText().equals(confirm_field.getText())) {
                UIManager.put("OptionPane.okButtonText", "Tamam");
                JOptionPane.showMessageDialog(rootPane, "Şifre ve şifreyi doğrulayın kısmı aynı olmalı");
                
            }
        
        if (userName_field.getText().length() == 0 && tckn_field.getText().length() != 0 && password_field.getText().length() != 0 && confirm_field.getText().length() != 0) {
            error1.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() == 0 && password_field.getText().length() != 0 && confirm_field.getText().length() != 0) {
            error2.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() != 0 && password_field.getText().length() == 0 && confirm_field.getText().length() != 0) {
            error3.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() != 0 && password_field.getText().length() != 0 && confirm_field.getText().length() == 0) {
            error4.setForeground(Color.red);
        } else if (userName_field.getText().length() == 0 && tckn_field.getText().length() == 0 && password_field.getText().length() != 0 && confirm_field.getText().length() != 0) {
            error1.setForeground(Color.red);
            error2.setForeground(Color.red);
        } else if (userName_field.getText().length() == 0 && tckn_field.getText().length() != 0 && password_field.getText().length() == 0 && confirm_field.getText().length() != 0) {
            error1.setForeground(Color.red);
            error3.setForeground(Color.red);
        } else if (userName_field.getText().length() == 0 && tckn_field.getText().length() != 0 && password_field.getText().length() != 0 && confirm_field.getText().length() == 0) {
            error1.setForeground(Color.red);
            error4.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() == 0 && password_field.getText().length() == 0 && confirm_field.getText().length() != 0) {
            error2.setForeground(Color.red);
            error3.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() == 0 && password_field.getText().length() != 0 && confirm_field.getText().length() == 0) {
            error2.setForeground(Color.red);
            error4.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() != 0 && password_field.getText().length() == 0 && confirm_field.getText().length() == 0) {
            error3.setForeground(Color.red);
            error4.setForeground(Color.red);
        } else if (userName_field.getText().length() == 0 && tckn_field.getText().length() == 0 && password_field.getText().length() == 0 && confirm_field.getText().length() == 0) {
            error1.setForeground(Color.red);
            error2.setForeground(Color.red);
            error3.setForeground(Color.red);
            error4.setForeground(Color.red);
           
        } else {
            try {
                if (password_field.getText().equals(confirm_field.getText())) {
                    String upperAd = userName_field.getText().substring(0, 1).toUpperCase() + userName_field.getText().substring(1);

                boolean control = hasta.addHasta(tckn_field.getText(), password_field.getText(), upperAd);
                if (control) {
                    UIManager.put("OptionPane.okButtonText", "Tamam");
                    JOptionPane.showMessageDialog(rootPane, "Kayıt başarılı", "Hasta Kayıt", JOptionPane.OK_OPTION, new ImageIcon(getClass().getResource("/icons/Done.png")));
                    userName_field.setText(null);
                    tckn_field.setText(null);
                    password_field.setText(null);
                    confirm_field.setText(null);
                }else{
                     UIManager.put("OptionPane.okButtonText", "Tamam");
                     JOptionPane.showMessageDialog(rootPane, "Kayıt Başarısız");
                }
            } 
                }catch (Exception e) {
                e.printStackTrace();
            }
                
        }


    }//GEN-LAST:event_btn_createActionPerformed

    private void tckn_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tckn_fieldActionPerformed


    }//GEN-LAST:event_tckn_fieldActionPerformed

    private void userName_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userName_fieldMouseClicked

    }//GEN-LAST:event_userName_fieldMouseClicked

    private void tckn_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tckn_fieldMouseClicked

    }//GEN-LAST:event_tckn_fieldMouseClicked

    private void userName_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName_fieldKeyPressed
        error1.setForeground(Color.WHITE);
    }//GEN-LAST:event_userName_fieldKeyPressed

    private void tckn_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tckn_fieldKeyPressed
        error2.setForeground(Color.WHITE);
    }//GEN-LAST:event_tckn_fieldKeyPressed

    private void password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyPressed
        error3.setForeground(Color.WHITE);
    }//GEN-LAST:event_password_fieldKeyPressed

    private void confirm_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_fieldKeyPressed
        error4.setForeground(Color.WHITE);
    }//GEN-LAST:event_confirm_fieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JPasswordField confirm_field;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label_geridön;
    private javax.swing.JLabel logınLogo;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField tckn_field;
    private javax.swing.JTextField userName_field;
    private javax.swing.JPanel w_panel;
    // End of variables declaration//GEN-END:variables
}
